### ISSUE TITLE
google is not defined error

### ISSUE THREAD

**Issue by deepakparamesh** [ultrasonicsoft/gmap-ng5#2]
Everything is working fine but getting the error in the console as

`ERROR ReferenceError: google is not defined`

and It is taking time to show the map (around 10-15 sec). Is there any solution to rectify it ?

**Comment by ultrasonicsoft** [comment]
Looks like repeated issue:
https://github.com/ultrasonicsoft/gmap-ng5/issues/1

Regarding speed, try below steps:
1. Comment out <script src="http://maps.googleapis.com/maps/api/js"></script> in index.html
2. Download http://maps.googleapis.com/maps/api/js javascript file and save as "gmaps.js" inside "assets" folder
3. Update "scripts" section of .angular-cli.json file by adding:
        "assets/gmaps.js"
4. Restart 'ng serve'
This should improve performance.

**Comment by deepakparamesh** [comment]
Thanks a lot sir, your response helped me.
