### ISSUE TITLE
ERROR ReferenceError: google is not defined

### ISSUE THREAD

**Issue by billakrishan** [ultrasonicsoft/gmap-ng5#3]
Hi Balram,
I am using agm/core for implementing google maps in my application. I have a service in which I have a getAddress method which inputs lat and lng and tries to converts it to the address.  
And this is the code for it.
import { } from '@types/googlemaps';
declare const google: any;
public getAddress(lat, lng) {

    const latlng = {lat: parseFloat(lat), lng: parseFloat(lng)};
    const geocoder = new google.maps.Geocoder();
    geocoder.geocode({'location': latlng}, function(results, status) {
            this.address = results[0].formatted_address;
      });

      return this.address;

    }
In that, I get google is not found error.

Any help is appericiated. 

![untitled](https://user-images.githubusercontent.com/24254032/38110775-b853dfb4-336a-11e8-9382-c22467407953.png)

**Comment by ultrasonicsoft** [comment]
Hi,
Have you installed types for Google maps?
Check your package.json file for reference. Also try to create a GitHub repo where I can reproduce this issue.

**Comment by billakrishan** [comment]
Hi Balram,
Thanks for getting back. Yes, it was that issue and it is fixed now.
Another quick question, I want to convert this Angular 5 app now to a Cordova mobile application with some plugins. 

Please advise if you know any better way of doing this.

Thanks,
Krishan

**Comment by ultrasonicsoft** [comment]
If you just want to convert then it's simple. But if you want to add some Cordova plugin then you will need to do install it's types and plugins. 
May be I can try to write a blog with example for the same.

**Comment by billakrishan** [comment]
Hi Balram,
I have managed to covert it to a cordova app and it works fine. I am just trying to find a way to add plugins.
I have done this in app-component so far, but doesn’t work

import { Component , OnInit} from ‘@angular/core’;
….
….
export class AppComponent implements OnInit{
 ngOnInit() {
 document.addEventListener(“deviceready”, function() {
 alert(device.platform);
 }, false);
 }
}

Please advise.
Thanks,
Krishan


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ultrasonicsoft** [comment]
Try to add code on ngAfterViewInit event rather than onInit
